import {
  Entity,
  Column,
  ManyToOne,
  OneToMany,
  JoinColumn,
  Index,
} from 'typeorm';
import { BaseEntity } from '../../common/entities/BaseEntity';
import { Company } from '../companies/company.entity';
import { Customer } from '../customers/customer.entity';
import { Branch } from '../branches/branch.entity';
import { User } from '../users/user.entity';
import { InvoiceItem } from './invoice-item.entity';
import { Payment } from '../payments/payment.entity';
import { InvoiceLog } from './invoice-log.entity';

export enum InvoiceStatus {
  DRAFT = 'draft',
  SUBMITTED = 'submitted',
  ACCEPTED = 'accepted',
  REJECTED = 'rejected',
  PAID = 'paid',
  OVERDUE = 'overdue',
  CANCELLED = 'cancelled',
}

export enum InvoiceType {
  INVOICE = 'i',          // ETA "i" — B2B/B2G electronic invoice
  CREDIT_NOTE = 'c',
  DEBIT_NOTE = 'd',
  RECEIPT = 'r',          // ETA "r" — B2C electronic receipt (POS-style)
}

@Entity({ name: 'invoices' })
@Index(['companyId', 'invoiceNumber'], { unique: true })
@Index(['companyId', 'status'])
@Index(['companyId', 'etaUuid'])
export class Invoice extends BaseEntity {
  @Column({ type: 'varchar', length: 60 })
  invoiceNumber!: string; // internal sequential

  @Column({ type: 'enum', enum: InvoiceType, default: InvoiceType.INVOICE })
  type!: InvoiceType;

  @Column({ type: 'enum', enum: InvoiceStatus, default: InvoiceStatus.DRAFT })
  status!: InvoiceStatus;

  @Column({ type: 'date' })
  issueDate!: string; // YYYY-MM-DD

  @Column({ type: 'date', nullable: true })
  dueDate?: string | null;

  @Column({ type: 'varchar', length: 10, default: 'EGP' })
  currency!: string;

  @Column({ type: 'decimal', precision: 18, scale: 4, default: 0 })
  subtotal!: number;

  @Column({ type: 'decimal', precision: 18, scale: 4, default: 0 })
  totalDiscount!: number;

  @Column({ type: 'decimal', precision: 18, scale: 4, default: 0 })
  totalTax!: number;

  @Column({ type: 'decimal', precision: 18, scale: 4, default: 0 })
  total!: number;

  @Column({ type: 'decimal', precision: 18, scale: 4, default: 0 })
  amountPaid!: number;

  @Column({ type: 'text', nullable: true })
  notes?: string;

  // ETA data
  @Column({ type: 'varchar', length: 80, nullable: true })
  etaUuid?: string;

  @Column({ type: 'varchar', length: 80, nullable: true })
  etaLongId?: string;

  @Column({ type: 'varchar', length: 80, nullable: true })
  etaSubmissionId?: string;

  @Column({ type: 'varchar', length: 200, nullable: true })
  etaInternalId?: string;

  @Column({ type: 'text', nullable: true })
  etaErrors?: string;

  @Column({ type: 'timestamp', nullable: true })
  etaSubmittedAt?: Date | null;

  // foreign keys
  @Column({ type: 'char', length: 36 })
  companyId!: string;

  @Column({ type: 'char', length: 36 })
  customerId!: string;

  @Column({ type: 'char', length: 36, nullable: true })
  branchId?: string | null;

  @Column({ type: 'char', length: 36, nullable: true })
  createdById?: string | null;

  @Column({ type: 'char', length: 36, nullable: true })
  recurringId?: string | null;

  @Column({ type: 'boolean', default: false })
  isAutoGenerated!: boolean;

  @ManyToOne(() => Company, (c) => c.invoices, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'companyId' })
  company!: Company;

  @ManyToOne(() => Customer, (c) => c.invoices, { onDelete: 'RESTRICT' })
  @JoinColumn({ name: 'customerId' })
  customer!: Customer;

  @ManyToOne(() => Branch, { onDelete: 'SET NULL', nullable: true })
  @JoinColumn({ name: 'branchId' })
  branch?: Branch | null;

  @ManyToOne(() => User, (u) => u.createdInvoices, { onDelete: 'SET NULL', nullable: true })
  @JoinColumn({ name: 'createdById' })
  createdBy?: User | null;

  @OneToMany(() => InvoiceItem, (i) => i.invoice, { cascade: true })
  items!: InvoiceItem[];

  @OneToMany(() => Payment, (p) => p.invoice)
  payments!: Payment[];

  @OneToMany(() => InvoiceLog, (l) => l.invoice)
  logs!: InvoiceLog[];
}
